name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

    # checkout code
    - name: checkout
      uses: actions/checkout@v1

    # install dependencies
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libtirpc-dev libboost-program-options-dev

    # build
    - name: Build
      run: g++ -m64 -I/usr/include/tirpc main.cpp -o /tmp/fakenfs -lstdc++ -lboost_program_options -ltirpc

    # release
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: /tmp/fakenfs