name: Test Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

    # checkout code
    - name: checkout
      uses: actions/checkout@v1

    # install dependencies
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libc6-dev libboost-program-options-dev

    # build
    - name: Build
      run: g++ -m64 main.cpp -o /tmp/fakenfs -lstdc++ -lboost_program_options